# Generated by Django 5.1 on 2024-08-17 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizscores_alter_quizquestions_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscores',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 17)),
        ),
    ]
